CC= g++ -c 

all: code

code: controllers.o structures.o algorithm.o interfaces.o main.o
	g++ *.o -o code
	
main.o: 
	$(CC) ./main.cpp
 
controllers.o: 
	$(CC) ./controllers/*.cpp
#BitInStream.cpp ./controllers/BitOutStream.cpp

structures.o:
	$(CC) ./structures/*.cpp
#FiniteBuffer.cpp ./structures/Nodo.cpp

algorithm.o:
	$(CC) ./algorithm/*.cpp
#Huffman.cpp ./algorithm/lz77.cpp
interfaces.o:
	$(CC) ./interfaces/*.cpp

clean:
	rm *.o code
