CC= g++ -c 

all: code

code: controllers.o method.o structures.o algorithm.o main.o
	g++ *.o -o code
	
main.o: 
	$(CC) ./main.cpp
 
controllers.o: 
	$(CC) ./controllers/*.cpp
#BitInStream.cpp ./controllers/BitOutStream.cpp

method.o:
	$(CC) ./method/*.cpp
#Method.cpp ./method/byteMethod.cpp ./method/huffmanMethod.cpp 

structures.o:
	$(CC) ./structures/*.cpp
#FiniteBuffer.cpp ./structures/Nodo.cpp

algorithm.o:
	$(CC) ./algorithm/*.cpp
#Huffman.cpp ./algorithm/lz77.cpp
	
clean:
	rm *.o code
